{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ include "drl.namespace" . }}
  labels:
    app: {{ .Values.redis.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          args:
{{ toYaml .Values.redis.args | indent 12 }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
{{- end }}
